"""base de datos

Revision ID: 4ff035eafe6f
Revises: bb80d19f57e4
Create Date: 2022-05-17 15:31:31.131708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff035eafe6f'
down_revision = 'bb80d19f57e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
